---
title: "Historia Gráfica del Conflicto Armado Colombiano (1958-2018)"
author: "Grupo de Investigación *Suma Yuyai*"
date: "2020" # "7/12/2020"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    theme: "cerulean"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Presentación

A 30 de junio de 2020 se contabilizan 9,031,048 víctimas del conflicto armado según la [Unidad para la Atención y Reparación Integral a las Víctimas](https://www.unidadvictimas.gov.co) (UARIV). Los hechos victimizantes con mayor frecuencia registrada son los de desplazamiento forzado (8.047.756), homicidios (1.044.399) y amenazas (502.005). No obstante, existen otros hechos a los que debe prestársele atención en aras de interpretar mejor las dinámicas de la guerra vivida en Colombia durante las últimas décadas.

Sin embargo, de los datos concernientes al Registro Único de Víctimas (RUV), de donde resultan las citadas cifras, solo se publican las sumas totales de hechos acaecidos a partir de enero de 1985. Datos que aún no están disponibles para su descarga y análisis independiente. Con todo, ofrecen una primera evidencia del enorme impacto que el conflicto armado colombiano ha generado desde mucho tiempo atrás.

Aunque no todo está perdido para un análisis basado en datos acerca de un problema que ha afectado y afecta por lo menos a 20 por ciento de la población colombiana. Una afectación que reclama todavía múltiples esfuerzos para su esclarecimiento desde los diversos sectores sociales, especialmente de aquellos que vivieron y continúan viviendo las secuelas de la agresión y la violencia.  

En efecto, este es un proyecto abierto y colaborativo que busca una comprensión renovada del conflicto armado colombiano. Se pretende elaborar una historia interactiva y participativa de seis décadas de guerra en Colombia (1958-2018). Una tarea apalancada en formas contemporáneas del periodismo que exigen un trabajo especial en el manejo y procesamiento de grandes cantidades de datos, donde se esconden múltiples historias. La idea básica es pescar esos relatos en tal océano de información y presentarlos gráficamente al público en diversas plataformas.

Se dice abierto pues sus datos y código fuente están disponibles en línea para su consulta y pueden ser usados bajo la Licencia Pública General ([GPL](LICENSE), por su sigla en inglés). Para ello se creó un repositorio con tales archivos en GitHub, al que se puede acceder libremente por medio de la carpeeta del proyecto en el siguiente enlace: <https://github.com/investiga/hgca>. Este hecho habilita sustancialmente la posibilidad de participar en una labor conjunta, sincrónica y asincrónica, sobre la temática propuesta. Por lo demás, permite que los avances realizados vayan acumulándose en el futuro y puedan ser cotinuados por futuros investigadores y periodistas interesados en ella.

## Sobre los datos base del proyecto

La base de datos más completa y disponible hasta el momento sobre la materia tratada es la publicada por el Centro Nacional de Memoria Histórica (CNMH) el año pasado. Este centro de memoria histórica fue creado mediante la [Ley 1448 de 2011](https://www.unidadvictimas.gov.co/sites/default/files/documentosbiblioteca/ley-1448-de-2011.pdf) en la que se adoptaron medidas de "atención, asistencia y reparación integral a las víctimas del conflicto armado interno". En 2019 el [Observatorio de Memoria y Conflicto](http://centrodememoriahistorica.gov.co/observatorio/), adscrito a dicha entidad, puso en línea la base de datos en su página electrónica para consulta y descarga. Los registros abarcan desde enero de 1958 hasta septiembre de 2018 y responden al mandato estipulado en dicha ley sobre el fortalecimiento de la memoria colectiva acerca de los fenómenos de violencia en la historia reciente. Del mismo modo, se encuentran allí los documentos referentes a la metodología de análisis de las variables incluidas en los datos.

Para una consulta detallada sobre la metodología de recopilación se aconseja revisar el el tomo de [diccionarios de las bases de datos del Observatorio de Memoria y Conflicto](http://centrodememoriahistorica.gov.co/observatorio/wp-content/uploads/2016/09/Diccionarios-Bases-de-Datos-Observatorio-de-Memoria-y-Conflicto-1.pdf) y el [marco conceptual](http://centrodememoriahistorica.gov.co/observatorio/wp-content/uploads/2016/09/Marco-Conceptual-Observatorio-de-Memoria-y-Conflicto-1.pdf), pensado allí como una plataforma que integra fuentes sociales e institucionales que contribuyen al esclarecimiento histórico y la memoria sobre el conflicto armado colombiano.

Antes de empezar la labor analítica se debieron organizar los datos en bruto para su procesamiento en R. Estos sets de datos se importan fácilmente a través del script all_df.R. En cuanto a all_c.R y all_v.R, agregan la información de cada una de las tablas de casos y víctimas, respectivamente, creadas con all_df.R. De ese modo, se accede a la cuantificación global en las categorías de casos y víctimas.

La colección se compone entonces por 22 hojas de cálculo de casos y víctimas de acciones bélicas (AB), asesinatos selectivos (AS), ataques a poblados (AP). atentados terroristas (AT), daño a bienes civiles (DB), desaparición forzada (DF), masacres (MA), reclutamiento y utilización de menores (RU), secuestro (SE), violencia sexual (VS) y eventos por minas antipersonal (MI). En total se registran 764.720 observaciones, 352.786 de casos y 411.934 de víctimas. 

En el total de registros de víctimas se presentan 798 duplicados, 15 triplicados y 1 cuadruplicado (que suman 831 repeticiones). Estas repeticiones se deben, en varios casos a que algunas de las víctimas lo fueron en más de una ocasión. La revision de estas repeticiones queda en abierto para indagar en detalle qué paso con cada una de ellas. Por el momento, al revisar el unico registro cuadruple (Id 482938) de la colección, se encontró el caso de un civil de 18 a 28 años, en San Pablo, Bolívar, afectado el 22 de junio de 2001 y, nuevamente, el 9 de septiembre de 2005 en Coveñas, Sucre.  En el primer hecho, con presunta responsabilidad de las Autodefensas Unidas de Colombia (AUC), hubo tortura e intimidación, mientras que el segundo anota que hubo pago por liberación sin definir un grupo responsable. Los otros dos registros corresponden a una repetición  del primer hecho ocurrido en San Pablo o a una situación extraordinaria de este caso en particular. 

En consecuencia, se decidió incluir todos los registros de casos y víctimas sin restar, por el momento, tales repeticiones del conteo global mientras no se sepa a ciencia cierta el porqué aparecen así en la base de datos.

Todo lo anterior refuerza la necesidad del trabajo colaborativo para avanzar en la tarea propuesta de construcción de una historia renovada del conflicto armado colombiano. La periodización propuesta y las secciones complementarias se pueden consultar en [Veinte mil días de guerra](https://github.com/investiga/hgca/20mil).

## Sobre el grupo de investigación *Suma Yuyai*

El grupo de investigación [*Suma Yuyai*](https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000021049) se crea en 2013 como un proyecto de la [Fundación Ridcharí Indígena](https://fridchari.blogspot.com/). Esta organización busca mejorar la calidad de vida y la participación ciudadana de las poblaciones más vulnerables socialmente, empresarios y comunidades a través de la implementación de planes, programas y proyectos de diversa índole, que posibiliten el bienestar comunitario y el desarrollo sostenible en los ámbitos de acción, organización y producción humana. Para avanzar en este propósito el proyecto aquí propuesto incentiva la participación ciudadana de las víctimas del conflicto armado colombiano como base para la construcción de un país reconciliado y en paz.

*Suma Yuyai* es un grupo registrado ante el Ministerio de Ciencia, Tecnología e Innovación en espera de categorización y esta propuesta se adscribe a la línea de investigación [*Historiografías del Abya Yala*](https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000021049), la cual hace parte de su plan estratégico como colectivo de pesquisa científica. Además, siguiendo el espíritu abierto y colaborativo de la iniciativa historiográfica propuesta, animamos a quienes quieran participar activamente para que se integren a él.

## A los futuros colaboradores

Como se señaló al comienzo, la tarea de construir una comprensión histórica del conflicto armado reciente en Colombia es inmensa. Es también una deuda para con las millones de víctimas de atrocidades y hechos violentos ocurridos en medio de la guerra. Por ello, reiteramos la invitación a quienes quieran unirse al equipo que hoy asume dicha tarea para que nos acompañen en esta expedición. Además del repositorio creado en [GitHub](https://github.com/investiga/hgca) y las páginas electrónicas del proyecto, los interesados pueden comunicarse también a los correos ridchari@gmail.com o nukajames@gmail.com.

Sean bienvenid@s a [Veinte mil días de guerra](https://github.com/investiga/hgca/20mil/).